## ---------------------------
##
## Script name: ReadReview
##
## Purpose of script: Reads in a single trip's catch review file from the EM
##    project. The files are produced by NOAA staff following NOAA's audit of
##    the EM service provider's review for the trip.
##
## Author: Dr. George A. Maynard
##
## Date Created: 2020-05-20
##
## Copyright (c) George Alphonse Maynard, 2020
## Email: galphonsemaynard@gmail.com
##
## ---------------------------
##
## Notes:
##   
##
## ---------------------------

## set working directory
  ## In this instance, the working directory should already be set to the 
  ## github repository https://github.com/gamaynard/-catchReview.git
## ---------------------------

## Set options
options(scipen = 6, digits = 4) # eliminate scientific notation
## ---------------------------

## load up the packages we will need:  (uncomment as required)
library(XLConnect)
library(lubridate)
## ---------------------------

## load up our functions into memory

## ---------------------------

## Set the filename to read in
filename="../Catch Reviews FY19-20200512T202011Z-001/Catch Reviews FY19/Catch_review_20190430_KathrynLeigh.xlsx"
## The first sheet of the file is the provider data
provider=readWorksheetFromFile(
  file=filename,
  sheet=1,
  startRow=1,
  endCol=17
)
## Format the data
provider$ID=as.numeric(as.character(provider$ID))
provider$Timestamp=ymd_hms(as.character(provider$Timestamp))
provider$Latitude=as.numeric(as.character(provider$Latitude))
provider$Longitude=as.numeric(as.character(provider$Longitude))
provider$Description=as.character(provider$Description)
provider$Comments=as.character(provider$Comments)
provider$Estimated.by=as.character(provider$Estimated.by)
provider$Estimated.weight=as.numeric(as.character(provider$Estimated.weight))
provider$INC.life.status=as.character(provider$INC.life.status)
provider$Discard.Condition=as.character(provider$Discard.Condition)
provider$Length=as.numeric(as.character(provider$Length))
provider$Quantity=as.numeric(as.character(provider$Quantity))
provider$Retained=as.character(provider$Retained)
provider$Species=as.character(provider$Species)
provider$Gear.Type=as.character(provider$Gear.Type)
provider$Reviewer=as.character(provider$Reviewer)
provider$Vessel=as.character(provider$Vessel)

## The second worksheet is the FSB (NOAA Fisheries Sampling Branch) review
fsb=readWorksheetFromFile(
  file=filename,
  sheet=2,
  startRow=1,
  endCol=17
)
## Format the data
fsb$ID=as.numeric(as.character(fsb$ID))
fsb$Timestamp=ymd_hms(as.character(fsb$Timestamp))
fsb$Latitude=as.numeric(as.character(fsb$Latitude))
fsb$Longitude=as.numeric(as.character(fsb$Longitude))
fsb$Description=as.character(fsb$Description)
fsb$Comments=as.character(fsb$Comments)
fsb$Estimated.by=as.character(fsb$Estimated.by)
fsb$Estimated.weight=as.numeric(as.character(fsb$Estimated.weight))
fsb$INC.life.status=as.character(fsb$INC.life.status)
fsb$Discard.Condition=as.character(fsb$Discard.Condition)
fsb$Length=as.numeric(as.character(fsb$Length))
fsb$Quantity=as.numeric(as.character(fsb$Quantity))
fsb$Retained=as.character(fsb$Retained)
fsb$Species=as.character(fsb$Species)
fsb$Gear.Type=as.character(fsb$Gear.Type)
fsb$Reviewer=as.character(fsb$Reviewer)
fsb$Vessel=as.character(fsb$Vessel)

## Standardize species between provider and fsb data sheets
species=read.csv("species.csv")
fsb$SPECIES=NA
for(i in 1:nrow(fsb)){
  if(fsb$Species[i]%in%species$FSB1){
    fsb$SPECIES[i]=as.character(species$AFS[which(fsb$Species[i]==species$FSB1)])
  } else {
    if(fsb$Species[i]%in%species$FSB2){
      fsb$SPECIES[i]=as.character(species$AFS[which(fsb$Species[i]==species$FSB2)])
    } else {
      fsb$SPECIES[i]=NA
    }
  }
}
provider$SPECIES=NA
for(i in 1:nrow(provider)){
  if(provider$Species[i]%in%species$Provider){
    provider$SPECIES[i]=as.character(species$AFS[which(provider$Species[i]==species$Provider)])
  } else {
    provider$SPECIES[i]=NA
  }
}
## The third through seventh sheets are generated by FSB and include some
## comparison metrics. Without knowing what their methodology is for matching
## data between the two raw sheets (provider and fsb), it's hard to say anything
## about the value of these sheets. 

## The eighth sheet in the workbook is a summary file that is essentially a
## block of text, presumably produced by the FSB reviewer, describing any
## discrepencies between the outputs of the two reviews
fsbSummary=readWorksheetFromFile(
  file=filename,
  sheet=8,
  startRow=0
)
fsbSummary=colnames(fsbSummary)
## Make the text string human readable
fsbSummary=gsub(
  pattern="\\.\\.",
  replacement="\\! ",
  x=fsbSummary
)
fsbSummary=gsub(
  pattern="\\.",
  replacement=" ",
  x=fsbSummary
)
fsbSummary=gsub(
  pattern="\\!",
  replacement="\\.",
  x=fsbSummary
)
## ---------------------------

## Create a blank reconciliation table
recon=data.frame(
  p_Timestamp=character(),
  f_Timestamp=character(),
  p_Lat=double(),
  f_Lat=double(),
  p_Lon=double(),
  f_Lon=double(),
  p_Desc=character(),
  f_Desc=character(),
  p_Com=character(),
  f_Com=character(),
  p_Wgt=double(),
  f_Wgt=double(),
  p_Len=double(),
  f_Len=double(),
  p_Quan=integer(),
  f_Quan=integer(),
  SPECIES=character(),
  p_Rev=character(),
  f_Rev=character(),
  notes=character(),
  stringsAsFactors=FALSE
)
recon[0:nrow(provider),]=NA
## Set parameters for comparison
## Time Tolerance (seconds)
timeTolerance=2
## Latitude Tolerance (decimal degrees)
## Longitude Tolerance (decimal degrees)
for(i in 1:nrow(provider)){
  p=provider[i,]
  recon$p_Timestamp[i]=as.character(ymd_hms(p$Timestamp))
  recon$p_Lat[i]=p$Latitude
  recon$p_Lon[i]=p$Longitude
  recon$p_Desc[i]=p$Description
  recon$p_Com[i]=p$Comments
  f=subset(fsb,fsb$Timestamp%in%seq(p$Timestamp-timeTolerance,p$Timestamp+timeTolerance,1))
  
}