## ---------------------------
##
## Script name: ReadReview
##
## Purpose of script: Reads in a single trip's catch review file from the EM
##    project. The files are produced by NOAA staff following NOAA's audit of
##    the EM service provider's review for the trip.
##
## Author: Dr. George A. Maynard
##
## Date Created: 2020-05-20
##
## Copyright (c) George Alphonse Maynard, 2020
## Email: galphonsemaynard@gmail.com
##
## ---------------------------
##
## Notes:
##   
##
## ---------------------------

## set working directory
  ## In this instance, the working directory should already be set to the 
  ## github repository https://github.com/gamaynard/-catchReview.git
## ---------------------------

## Set options
options(scipen = 6, digits = 4) # eliminate scientific notation
memory.limit(30000000)     # increase PC memory allowance
## ---------------------------

## load up the packages we will need:  (uncomment as required)
library(XLConnect)
library(lubridate)
## ---------------------------

## load up our functions into memory

## ---------------------------

## Set the filename to read in
filename="../Catch Reviews FY19-20200512T202011Z-001/Catch Reviews FY19/Catch_review_20190430_KathrynLeigh.xlsx"
## The first sheet of the file is the provider data
provider=readWorksheetFromFile(
  file=filename,
  sheet=1,
  startRow=1,
  endCol=17
)
## Format the data
provider$ID=as.numeric(as.character(provider$ID))
provider$Timestamp=ymd_hms(as.character(provider$Timestamp))
provider$Latitude=as.numeric(as.character(provider$Latitude))
provider$Longitude=as.numeric(as.character(provider$Longitude))
provider$Description=as.character(provider$Description)
provider$Comments=as.character(provider$Comments)
provider$Estimated.by=as.character(provider$Estimated.by)
provider$Estimated.weight=as.numeric(as.character(provider$Estimated.weight))
provider$INC.life.status=as.character(provider$INC.life.status)
provider$Discard.Condition=as.character(provider$Discard.Condition)
provider$Length=as.numeric(as.character(provider$Length))
provider$Quantity=as.numeric(as.character(provider$Quantity))
provider$Retained=as.character(provider$Retained)
provider$Species=as.character(provider$Species)
provider$Gear.Type=as.character(provider$Gear.Type)
provider$Reviewer=as.character(provider$Reviewer)
provider$Vessel=as.character(provider$Vessel)

## The second worksheet is the FSB (NOAA Fisheries Sampling Branch) review
fsb=readWorksheetFromFile(
  file=filename,
  sheet=2,
  startRow=1,
  endCol=17
)
## Format the data
fsb$ID=as.numeric(as.character(fsb$ID))
fsb$Timestamp=ymd_hms(as.character(fsb$Timestamp))
fsb$Latitude=as.numeric(as.character(fsb$Latitude))
fsb$Longitude=as.numeric(as.character(fsb$Longitude))
fsb$Description=as.character(fsb$Description)
fsb$Comments=as.character(fsb$Comments)
fsb$Estimated.by=as.character(fsb$Estimated.by)
fsb$Estimated.weight=as.numeric(as.character(fsb$Estimated.weight))
fsb$INC.life.status=as.character(fsb$INC.life.status)
fsb$Discard.Condition=as.character(fsb$Discard.Condition)
fsb$Length=as.numeric(as.character(fsb$Length))
fsb$Quantity=as.numeric(as.character(fsb$Quantity))
fsb$Retained=as.character(fsb$Retained)
fsb$Species=as.character(fsb$Species)
fsb$Gear.Type=as.character(fsb$Gear.Type)
fsb$Reviewer=as.character(fsb$Reviewer)
fsb$Vessel=as.character(fsb$Vessel)

## The third through seventh sheets are generated by FSB and include some
## comparison metrics. Without knowing what their methodology is for matching
## data between the two raw sheets (provider and fsb), it's hard to say anything
## about the value of these sheets. 

## The eighth sheet in the workbook is a summary file that is essentially a
## block of text, presumably produced by the FSB reviewer, describing any
## discrepencies between the outputs of the two reviews
fsbSummary=readWorksheetFromFile(
  file=filename,
  sheet=8,
  startRow=1
)
## ---------------------------