## ---------------------------
##
## Script name: ReviewAnalysis
##
## Purpose of script: This script analyzes the summarized / standardized trip
##    values generated by ReviewLoop.R
##
## Author: George A. Maynard
##
## Date Created: 2020-05-27
##
## Copyright (c) George Alphonse Maynard, 2020
## Email: galphonsemaynard@gmail.com
##
## ---------------------------
##
## Notes:
##   
##
## ---------------------------

## set working directory
## In this instance, the working directory should already be set to the 
## github repository https://github.com/gamaynard/-catchReview.git
## ---------------------------

## Set options
options(scipen = 6, digits = 4) # eliminate scientific notation
## ---------------------------

## load up the packages we will need:  (uncomment as required)
library(lubridate)
## ---------------------------

## load up our functions into memory

## ---------------------------

## Run the ReviewLoop.R script to generate the rSum file
source("ReviewLoop.R")

## Create a unique identifier for each trip by combining the ordinal date and
## vessel name
rSum$TRIPID=paste(yday(ymd(as.character(rSum$DATE))),rSum$VESSEL,sep="_")

## Create a total fish within 2cm column
rSum$ALL_W2=as.numeric(as.character(rSum$EXACT_LENGTH))+as.numeric(as.character(rSum$W2_LENGTH),na.rm=TRUE)

## Create an empty dataframe to store results
## Create an empty dataframe to store results
data=data.frame(
  DataSet=character(),
  nTrips=integer(),
  totalFSBCount=integer(),
  totalTFCount=integer(),
  totalCountDiff=integer(),
  avgCountDiff=double(),
  minCountDiff=integer(),
  maxCountDiff=integer(),
  minCountDiff95=integer(),
  maxCountDiff95=integer(),
  totalFSBWeight=double(),
  totalTFWeight=double(),
  avgWeightDiff=double(),
  minWeightDiff=double(),
  maxWeightDiff=double(),
  minWeightDiff95=double(),
  maxWeightDiff95=double(),
  nFish=integer(),
  exact=integer(),
  w2=integer()
)
cn=colnames(data)
## Select a subset of interest (can be "unk","all","groundfish", "fish", or a
## species name from the list of standardized species names). 
for(soi in c("all","groundfish","unk","fish","ATLANTIC COD","POLLOCK","HADDOCK",
  "AMERICAN PLAICE","OCEAN POUT","REDFISH","WHITE HAKE","YELLOWTAIL FLOUNDER",
  "WINTER FLOUNDER","WINDOWPANE")){
  ## subset out only the rSum values indicated by the soi
  if(toupper(soi)=="ALL"){
    s=rSum
  } else {
    if(toupper(soi)=="GROUNDFISH"){
      s=subset(rSum,rSum$SPECIES%in%subset(species,species$GROUNDFISH==TRUE)$AFS)
    } else {
      if(toupper(soi)=="UNK"){
        s=subset(rSum,grepl("UNKNOWN",rSum$SPECIES))
      } else {
        if(toupper(soi)=="FISH"){
          s=subset(rSum,rSum$SPECIES%in%c("PINNIPED","MARINE MAMMAL","BIRD","NON-FISH")==FALSE)
        } else {
          s=subset(rSum,rSum$SPECIES==soi)
        }
      }
    }
  }
  
  ## Count the number of trips in the dataset
  nTrips=length(unique(s$TRIPID))
  ## Sum all FSB counts
  totalFSBCount=sum(as.numeric(as.character(s$FSB_COUNT)),na.rm=TRUE)
  ## Sum all TF counts
  totalTFCount=sum(as.numeric(as.character(s$TF_COUNT)),na.rm=TRUE)
  ## Calculate the overall difference in counts
  totalCountDiff=abs(totalFSBCount-totalTFCount)
  ## Calculate the average difference in counts per trip
  avgCountDiff=mean(as.numeric(as.character(s$DELTA_COUNT)),na.rm=TRUE)
  ## Calculate the range of differences in counts per trip
  rangeCountDiff=range(as.numeric(as.character(s$DELTA_COUNT)),na.rm=TRUE)
  ## Calculate the 95% CI of differences in counts per trip
  rangeCountDiff95=quantile(as.numeric(as.character(s$DELTA_COUNT)),na.rm=TRUE,c(0.025,0.975))
  ## Sum all FSB weights
  totalFSBWeight=sum(as.numeric(as.character(s$FSB_WEIGHT)),na.rm=TRUE)
  ## Sum all TF weights
  totalTFWeight=sum(as.numeric(as.character(s$TF_WEIGHT)),na.rm=TRUE)
  ## Calculate the overall difference in weights
  totalWeightDiff=abs(totalFSBWeight-totalTFWeight)
  ## Calculate the average difference in weights per trip
  avgWeightDiff=mean(as.numeric(as.character(s$DELTA_WEIGHT)),na.rm=TRUE)
  ## Calculate the range of weight differences per trip
  rangeWeightDiff=range(as.numeric(as.character(s$DELTA_WEIGHT)),na.rm=TRUE)
  ## Calculate the 95% CI of differences in weights per trip
  rangeWeightDiff95=quantile(as.numeric(as.character(s$DELTA_WEIGHT)),na.rm=TRUE,c(0.025,0.975))
  ## Sum total number of fish measured on all trips
  nFish=sum(as.numeric(as.character(s$IND_LENGTHS)),na.rm=TRUE)
  ## Sum total number of fish that matched exactly
  exact=sum(as.numeric(as.character(s$EXACT_LENGTH)),na.rm=TRUE)
  ## Sum total number of fish that were within 2 cm
  w2=sum(as.numeric(as.character(s$ALL_W2)),na.rm=TRUE)
  newline=matrix(nrow=1,ncol=20)
  newline[,1:20]=c(soi,nTrips,totalFSBCount,totalTFCount,totalCountDiff,
    avgCountDiff,rangeCountDiff,rangeCountDiff95,totalFSBWeight,totalTFWeight,
    avgWeightDiff,rangeWeightDiff,rangeWeightDiff95,nFish,exact,w2)
  data=rbind(data,newline)
}
colnames(data)=cn
data$pMatch=as.numeric(as.character(data$w2))/as.numeric(as.character(data$nFish))
## Write out the data to a .csv file
write.csv(data,"C:/Users/George/Desktop/Autotask Workplace/Electronic Monitoring/Georges Analyses/CatchReview/FY2019_summary.csv",row.names=FALSE)

## Plot the per trip count differences by species
par(mar=c(8, 4.1, 4.1, 2.1))
data=read.csv("C:/Users/George/Desktop/Autotask Workplace/Electronic Monitoring/Georges Analyses/CatchReview/FY2019_summary.csv")
data$DataSet=as.character(data$DataSet)
x=subset(data,data$DataSet%in%c('all','groundfish','unk','fish','WHITE HAKE')==FALSE)
x$pMatch=ifelse(x$pMatch>1,1,x$pMatch)
x=x[order(x$DataSet),]
y=barplot(
  height=x$avgCountDiff,
  names.arg=x$DataSet,
  beside=TRUE,
  las=2,
  ylim=c(0,35),
  ylab="Per Trip Count Differences",
  xlab="",
  cex.names=0.75,
  xaxt='n')
text(x=y,
     y=par("usr")[3]-1,
     srt=45,
     adj=1,
     labels=x$DataSet,
     xpd=TRUE)
text(x=y,
     y=x$maxCountDiff95+2,
     labels=paste("n=",x$nTrips,sep="")
)
segments(y, x$minCountDiff95, y,x$maxCountDiff95, lwd = 1.5)
arrows(y, x$minCountDiff95, y,x$maxCountDiff95,lwd = 1.5, angle = 90,code = 3, length = 0.05)
abline(h=seq(0,35,5),col='lightgray',lty=3)
abline(h=0,col='black',lty=1)

## Barplot of Fish Length Matching
y=barplot(height=x$nFish,
        col='lightgray',
        ylab='Number of Fish',
        ylim=c(0,5000)
        )
abline(h=seq(0,5000,1000),lty=3,col='lightgray')
barplot(height=x$w2,
        dens=10,
        angle=45,
        add=TRUE,
        col='black')
barplot(height=x$exact,
        dens=10,
        angle=135,
        add=TRUE,
        col='black')
legend(
  "topleft",
  legend=c("All","<2 cm","Exact"),
  fill=c('lightgray',NA,NA),
  dens=c(NA,20,20),
  col=c(NA,'black','black'),
  angle=c(NA,45,135)
)
text(x=y,
     y=x$nFish+500,
     labels=paste("p=",round(x$pMatch,2),sep="")
)
text(x=y,
     y=par("usr")[3]-1,
     srt=45,
     adj=1,
     labels=x$DataSet,
     xpd=TRUE)
abline(h=0,col='black')
